/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import MODEL.User;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.xml.stream.events.Comment;

/**
 *
 * @author Lenovo
 */
public class FormPanel extends javax.swing.JPanel {
    private Component rootPane;
    private JPanel bottomPanel;
   

    /**
     * Creates new form FormPanel
     */
    public FormPanel(JPanel inputPanel) {
        initComponents();
        JPanel bottomPanel1 = this.bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TITLELABEL = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        COMMENTLABEL = new javax.swing.JLabel();
        PatienttypeLabel = new javax.swing.JLabel();
        PatienttypeComboBox = new javax.swing.JComboBox<>();
        GenderLabel = new javax.swing.JLabel();
        FemaleRadio = new javax.swing.JRadioButton();
        MaleRadio = new javax.swing.JRadioButton();
        OtherRadio = new javax.swing.JRadioButton();
        CommentTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        TITLELABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TITLELABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITLELABEL.setText("PATIENT REGISTRATION FORM");

        FirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstNameLabel.setText("FIRST NAME:");

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastNameLabel.setText("LAST NAME:");

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AgeLabel.setText("AGE:");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("E-MAIL:");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        COMMENTLABEL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        COMMENTLABEL.setText("COMMENT:");

        PatienttypeLabel.setText("PATIENT TYPE:");

        PatienttypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEW PATIENT", "EXSITING PATIENT", " ", " " }));
        PatienttypeComboBox.setAutoscrolls(true);

        GenderLabel.setText("GENDER:");

        GenderGroup.add(FemaleRadio);
        FemaleRadio.setText("FEMALE");
        FemaleRadio.setActionCommand("FEMALE USER");

        GenderGroup.add(MaleRadio);
        MaleRadio.setText("MALE");
        MaleRadio.setActionCommand("MALE USER");

        GenderGroup.add(OtherRadio);
        OtherRadio.setText("OTHER");
        OtherRadio.setActionCommand("NOT SPECIFIED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(TITLELABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(COMMENTLABEL)
                            .addComponent(PatienttypeLabel)
                            .addComponent(GenderLabel))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PatienttypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(FirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(AgeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(FemaleRadio)
                            .addComponent(MaleRadio)
                            .addComponent(OtherRadio)
                            .addComponent(CommentTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TITLELABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(COMMENTLABEL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(CommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatienttypeLabel)
                    .addComponent(PatienttypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(FemaleRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OtherRadio)
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // System.out.println("hello");// TODO add your handling code here:
        User newUser = new User();
        newUser.setFirstName(FirstNameTextField.getText());
        newUser.setLastName(LastNameTextField.getText());
        newUser.setAge(AgeTextField.getText());
        newUser.setEmail(EmailTextField.getText());
        newUser.setGender(GenderGroup.getSelection().getActionCommand());
        newUser.setPatientType(PatienttypeComboBox.getSelectedItem().toString());
               try{
            Integer AgeValue = Integer.parseInt(Age);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter a number in age field");
        }

        String Email = EmailTextField.getText();
        String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$";
        Pattern pattern = Pattern.compile(emailPattern);
        Matcher matcher = pattern.matcher(Email);
        if (matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Email is valid.", "Validation Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please enter a valid email address.", "Validation Result", JOptionPane.ERROR_MESSAGE);
        }
        if (FirstName.isEmpty() || LastName.isEmpty() || AgeValue.isEmpty() || Email.isEmpty() || Comment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all values correctly", "Validation Error", JOptionPane.ERROR_MESSAGE);//System.out.println();
        }
        else{
            ImageIcon icon = new ImageIcon("C:\\Users\\Lenovo\\Downloads\\icon.png");
            String AgeValue = null;

            // Display the JOptionPane with the icon
            JOptionPane.showMessageDialog(this, "User Name: " + FirstName +" "+ LastName +" \n " + "Age: " + AgeValue +"\n" + "Email ID: " + Email +"\n" + "Comment: " + Comment, "USER INFORMATION",JOptionPane.INFORMATION_MESSAGE, icon);

        }

    }//GEN-LAST:event_SubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JLabel COMMENTLABEL;
    private javax.swing.JTextField CommentTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JRadioButton OtherRadio;
    private javax.swing.JComboBox<String> PatienttypeComboBox;
    private javax.swing.JLabel PatienttypeLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TITLELABEL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
